"""Add private client galleries

Revision ID: f05d01f687a7
Revises: 7342ad8b5a73
Create Date: 2026-09-30 11:28:36.601240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05d01f687a7'
down_revision: Union[str, Sequence[str], None] = '7342ad8b5a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cover_photo_id', sa.Integer(), nullable=True),
    sa.Column('is_download_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_favorites_enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['portfolio_photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleries_client_id'), 'galleries', ['client_id'], unique=False)
    op.create_index(op.f('ix_galleries_slug'), 'galleries', ['slug'], unique=True)
    op.create_table('gallery_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_access_access_token_hash'), 'gallery_access', ['access_token_hash'], unique=True)
    op.create_index(op.f('ix_gallery_access_client_id'), 'gallery_access', ['client_id'], unique=False)
    op.create_index(op.f('ix_gallery_access_gallery_id'), 'gallery_access', ['gallery_id'], unique=False)
    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_photo_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_photo_id'], ['portfolio_photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gallery_id', 'portfolio_photo_id', name='uq_gallery_photo')
    )
    op.create_index(op.f('ix_gallery_photos_gallery_id'), 'gallery_photos', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_gallery_photos_portfolio_photo_id'), 'gallery_photos', ['portfolio_photo_id'], unique=False)
    op.create_table('gallery_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('gallery_photo_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gallery_photo_id'], ['gallery_photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_downloads_client_id'), 'gallery_downloads', ['client_id'], unique=False)
    op.create_index(op.f('ix_gallery_downloads_gallery_id'), 'gallery_downloads', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_gallery_downloads_gallery_photo_id'), 'gallery_downloads', ['gallery_photo_id'], unique=False)
    op.create_table('gallery_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('gallery_photo_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gallery_photo_id'], ['gallery_photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gallery_id', 'gallery_photo_id', 'client_id', name='uq_gallery_favorite')
    )
    op.create_index(op.f('ix_gallery_favorites_client_id'), 'gallery_favorites', ['client_id'], unique=False)
    op.create_index(op.f('ix_gallery_favorites_gallery_id'), 'gallery_favorites', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_gallery_favorites_gallery_photo_id'), 'gallery_favorites', ['gallery_photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_favorites_gallery_photo_id'), table_name='gallery_favorites')
    op.drop_index(op.f('ix_gallery_favorites_gallery_id'), table_name='gallery_favorites')
    op.drop_index(op.f('ix_gallery_favorites_client_id'), table_name='gallery_favorites')
    op.drop_table('gallery_favorites')
    op.drop_index(op.f('ix_gallery_downloads_gallery_photo_id'), table_name='gallery_downloads')
    op.drop_index(op.f('ix_gallery_downloads_gallery_id'), table_name='gallery_downloads')
    op.drop_index(op.f('ix_gallery_downloads_client_id'), table_name='gallery_downloads')
    op.drop_table('gallery_downloads')
    op.drop_index(op.f('ix_gallery_photos_portfolio_photo_id'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_gallery_id'), table_name='gallery_photos')
    op.drop_table('gallery_photos')
    op.drop_index(op.f('ix_gallery_access_gallery_id'), table_name='gallery_access')
    op.drop_index(op.f('ix_gallery_access_client_id'), table_name='gallery_access')
    op.drop_index(op.f('ix_gallery_access_access_token_hash'), table_name='gallery_access')
    op.drop_table('gallery_access')
    op.drop_index(op.f('ix_galleries_slug'), table_name='galleries')
    op.drop_index(op.f('ix_galleries_client_id'), table_name='galleries')
    op.drop_table('galleries')
    # ### end Alembic commands ###
